### PR TITLE
Crude suggestions implementation

### PR DESCRIPTION
**Pull request by kalbhor**
Screenshot 2021-05-26 at 2 35 33 AM

### CODE REVIEW

**Comment by albatrosspreacher** [comment]
image

just me or (?) 🤔

**Comment by kalbhor** [comment]
Hmm this maybe due to difference in our operating system? I tested it on MacOS..

**Comment by albatrosspreacher** [comment]
I did too 👀

**Comment by kalbhor** [comment]
Damn, I may have to review my implementation 😪 
But auto suggestions sound like a nice idea right?

**Comment by albatrosspreacher** [comment]
Yeah, sounds pretty neat!

**Comment by albatrosspreacher** [comment]
Closing this request as there are no new developments. Please open a new request if needed!

**Pull request closed without merging**
